// Test generated by RoostGPT for test test1 using AI Model gpt

```go
package main

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestMain2b8a936782(t *testing.T) {
	t.Run("TestRootEndpoint", func(t *testing.T) {
		req, err := http.NewRequest("GET", "/", nil)
		if err != nil {
			t.Fatal(err)
		}

		rr := httptest.NewRecorder()
		handler := http.HandlerFunc(serveRoot)

		handler.ServeHTTP(rr, req)

		if status := rr.Code; status != http.StatusOK {
			t.Errorf("handler returned wrong status code: got %v want %v", status, http.StatusOK)
		}
	})

	t.Run("TestRunTestEndpoint", func(t *testing.T) {
		req, err := http.NewRequest("GET", "/tests/run", nil)
		if err != nil {
			t.Fatal(err)
		}

		rr := httptest.NewRecorder()
		handler := http.HandlerFunc(runTest)

		handler.ServeHTTP(rr, req)

		if status := rr.Code; status != http.StatusOK {
			t.Errorf("handler returned wrong status code: got %v want %v", status, http.StatusOK)
		}
	})
}