// Test generated by RoostGPT for test test1 using AI Model gpt

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"math/rand"
	"net"
	"net/http"
	"testing"
)

type Response struct {
	TotalVotes int `json:"total_votes"`
}

type Status struct {
	Code int `json:"code"`
}

type Vote struct {
	CandidateID string `json:"candidate_id"`
	VoterID     string `json:"voter_id"`
}

var (
	port = "8080" // TODO: Change this to the port where your service is running
)

func TestTestBallot9bbe2d8b8d(t *testing.T) {
	err := TestBallot()
	if err != nil {
		t.Error(err)
	}
}

func TestBallot() error {
	_, result, err := httpClientRequest(http.MethodGet, net.JoinHostPort("", port), "/", nil)
	if err != nil {
		log.Printf("Failed to get ballot count resp:%s error:%+v", string(result), err)
		return err
	}
	log.Println("get ballot resp:", string(result))
	var initalRespData Response
	if err = json.Unmarshal(result, &initalRespData); err != nil {
		log.Printf("Failed to unmarshal get ballot response. %+v", err)
		return err
	}

	var ballotvotereq Vote
	ballotvotereq.CandidateID = fmt.Sprint(rand.Intn(10))
	ballotvotereq.VoterID = fmt.Sprint(rand.Intn(10))
	reqBuff, err := json.Marshal(ballotvotereq)
	if err != nil {
		log.Printf("Failed to marshall post ballot request %+v", err)
		return err
	}

	_, result, err = httpClientRequest(http.MethodPost, net.JoinHostPort("", port), "/", bytes.NewReader(reqBuff))
	if err != nil {
		log.Printf("Failed to get ballot count resp:%s error:%+v", string(result), err)
		return err
	}
	log.Println("post ballot resp:", string(result))
	var postballotResp Status
	if err = json.Unmarshal(result, &postballotResp); err != nil {
		log.Printf("Failed to unmarshal post ballot response. %+v", err)
		return err
	}
	if postballotResp.Code != 201 {
		return errors.New("post ballot resp status code")
	}

	_, result, err = httpClientRequest(http.MethodGet, net.JoinHostPort("", port), "/", nil)
	if err != nil {
		log.Printf("Failed to get final ballot count resp:%s error:%+v", string(result), err)
		return err
	}
	log.Println("get final ballot resp:", string(result))
	var finalRespData Response
	if err = json.Unmarshal(result, &finalRespData); err != nil {
		log.Printf("Failed to unmarshal get final ballot response. %+v", err)
		return err
	}
	if finalRespData.TotalVotes-initalRespData.TotalVotes != 1 {
		return errors.New("ballot vote count error")
	}
	return nil
}

func httpClientRequest(method, url, path string, body io.Reader) (*http.Response, []byte, error) {
	req, err := http.NewRequest(method, url+path, body)
	if err != nil {
		return nil, nil, err
	}

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, nil, err
	}
	defer resp.Body.Close()

	resBody, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, err
	}

	return resp, resBody, nil
}