// Test generated by RoostGPT for test test1 using AI Model gpt

package main

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestMain2b8a936782(t *testing.T) {
	t.Run("test successful request to root", func(t *testing.T) {
		req, err := http.NewRequest("GET", "/", nil)
		if err != nil {
			t.Fatalf("Could not create request: %v", err)
		}
		rec := httptest.NewRecorder()
		serveRoot(rec, req)
		res := rec.Result()
		defer res.Body.Close()

		if res.StatusCode != http.StatusOK {
			t.Errorf("Expected status OK; got %v", res.Status)
		}
	})

	t.Run("test successful request to tests/run", func(t *testing.T) {
		req, err := http.NewRequest("GET", "/tests/run", nil)
		if err != nil {
			t.Fatalf("Could not create request: %v", err)
		}
		rec := httptest.NewRecorder()
		runTest(rec, req)
		res := rec.Result()
		defer res.Body.Close()

		if res.StatusCode != http.StatusOK {
			t.Errorf("Expected status OK; got %v", res.Status)
		}
	})

	t.Run("test unsuccessful request", func(t *testing.T) {
		req, err := http.NewRequest("GET", "/invalid/url", nil)
		if err != nil {
			t.Fatalf("Could not create request: %v", err)
		}
		rec := httptest.NewRecorder()
		serveRoot(rec, req)
		res := rec.Result()
		defer res.Body.Close()

		if res.StatusCode != http.StatusNotFound {
			t.Errorf("Expected status Not Found; got %v", res.Status)
		}
	})
}