// Test generated by RoostGPT for test test1 using AI Model gpt

package main

import (
	"bytes"
	"errors"
	"io"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestHttpClientRequestdae1710fc2(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`OK`))
	}))
	defer server.Close()

	t.Run("Success case", func(t *testing.T) {
		status, body, err := httpClientRequest("GET", server.URL, "/test", nil)
		if err != nil {
			t.Error("Expected no error, got ", err)
		}
		if status != http.StatusOK {
			t.Error("Expected status 200, got ", status)
		}
		if string(body) != "OK" {
			t.Error("Expected body 'OK', got ", string(body))
		}
	})

	t.Run("Error case", func(t *testing.T) {
		status, _, err := httpClientRequest("GET", "http://invalid url", "/test", nil)
		if err == nil {
			t.Error("Expected error, got nil")
		}
		if status != http.StatusBadRequest {
			t.Error("Expected status 400, got ", status)
		}
	})

	t.Run("POST request case", func(t *testing.T) {
		status, body, err := httpClientRequest("POST", server.URL, "/test", bytes.NewBufferString(`{"key": "value"}`))
		if err != nil {
			t.Error("Expected no error, got ", err)
		}
		if status != http.StatusOK {
			t.Error("Expected status 200, got ", status)
		}
		if string(body) != "OK" {
			t.Error("Expected body 'OK', got ", string(body))
		}
	})
}